
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingDB?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: profile
    profiles:
      active: "prod"
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9798/oauth/check_token
    client:
      client-id: mobile
      client-secret: 1234567
server:
  port: 8282




