spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingcloud_customer?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    # properties:
    #  hibernate:
    #   dialect: org.hibernate.dialect.MySQL55Dialect
#  application:
#    name: customer
