server:
  port: 9898
#spring:
#  security:
#    user:
#      name: ishara
#      password: 123456
#      roles: ADMIN,USER
#security:
#  oauth2:
#    client:
#      client-id: mobile
#      client-secret: pin
#      access-token-validity-seconds: 3000
#      authorized-grant-types: rerefresh_token,authorization_code,password,client_credentials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll
