spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingcloud_hotel?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: hotel
server:
  port: 9191