server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trniljk/booking-cloud-config-store
          search-paths:
            - '*service'
          #username: ishara
          #passphrase: 1234567