server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trniljk/spring-bookingcloud-config-store
          search-paths:
            - 'service-config/*service'
          #username: ishara
          #passphrase: 1234567