
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingcloud_booking?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#  application:
#    name: booking
server:
  port: 8181

